FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    cmake \
    g++ \
    gdb \
    make \
    git \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /project